read_blif datapath.blif

# inputs: START ACIDIFICA BASIFICA phI7 phI6 phI5 phI4 phI3 phI2 phI1 phI0

sim 1 0 0 0 0 0 0 0 0 0 0 # setto il registro a 0
echo RESET
echo --------------------

sim 1 0 1 0 1 1 0 0 1 0 0
echo START a 6.25 (soluzione acida)
echo basifica (6.25>6.5)
echo --------------------

sim 0 0 1 0 0 0 0 0 0 0 0 # pompo basico, phI a DC
echo basifica (6.5>6.75)
echo --------------------

sim 0 0 1 0 0 0 0 0 0 0 0 # pompo basico, phI a DC
echo basifica (6.75>7.0)
echo --------------------

sim 0 0 0 0 0 0 0 0 0 0 0 # phI a DC
sim 0 0 0 0 0 0 0 0 0 0 0 # phI a DC
echo fine, END a 1 (7.0>7.0)
echo NB: l output rimane uguale
echo --------------------
